name: calculadoranotas
description: "Um projeto de notas para usuario da FIAP"
publish_to: 'none'
version: 0.0.2+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
